---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme : cosmo
---

## Motivation

The overarching goal of this project was to analyze nutritional data collected for popular restaurants for any geographic trends (i.e. clusters of fast food restaurants in specific neighborhoods) in relation to potential health outcomes within NYC communities. The growing number of fast-food chains in the United States has pushed the US into an era of food "convenience." Since the industry’s inception in 1927, there are approximately 150 thousand convenience stores across the US as of 2020.1–3 Their presence is ubiquitous; however, little is known about the general distribution of fast-food chains in the US. In cities like New York there seems to be a new chain on every corner of the city. They provide quick and cheap food options, alongside fast food chains, which could be the only option for many communities. Convenience stores and fast food outlets alike are known to sell food products high in fats, sugars, and salts.7 The presence of convenience stores and fast food restaurants has been associated with higher BMI, higher obesity, and increased hypertension.8,9 Residents of color living in rural, low-income neighborhoods have inadequate access to supermarkets, chain grocery stores, and diversity in food products.10 

Fortunately, we were able to find a public dataset on over 100 popular national food chains and the menu items they each serve, spanning from 2008-2020. This dataset, the MenuStat nutritional database, was developed by the New York City Department of Health and Mental Hygiene. The food chain types include sit-down restaurants, fast food restaurants, convenience stores, and beverage and dessert shops. Thus, we were motivated by this data to investigate trends in NYC. We analyzed various trends in the nutritional content of the food available at 54 food chains of various types across New York City. 

## Related Work

When we began to think of how we wanted to analyze/visualize our data, we realized the Menustat data frame doesn’t have any information on the location of restaurants, just information on the menu items each food outlet offers. Since we were interested in understanding associations between neighborhood demographics and available food options, we needed data that included the locations of each food outlet. In class, we worked on the DOHMH New York City Restaurant Inspection Results data (NYC OpenData) that includes location information. That gave us the idea to use the Restaurants (rolled up) dataset from NYC OpenData because it includes location information that we used to identify the zip codes of each restaurant included in the Menustat data frame. This allowed us to approximate which food chains of various types and the nutritional content different NYC neighborhoods (zip codes) are exposed to. 

## Initial Questions

Most broadly, our team sought to investigate trends in nutritional content (i.e., total calories, fat, protein content, etc.) of menu items at popular fast-food chains over the timespan of 2008-2020 data. Within these data, we stratified by restaurant type (fast-food, convenience store, sit-down). Additionally, we wanted to look at the spatial distribution of fast-food chains and convenience stores within the five boroughs of New York City, in relation to demographic composition of the neighborhoods in which they are located. 

## Data

The data used for this project came from the following publicly available sources: 

[NYC DOHMH MenuStat nutritional database](https://www.menustat.org/data.html) 
  Menustat provides restaurant nutritional data for specific foods and beverages served at national chains. Some of these national chains do not have a presence in NYC, so filtering those out was one of the first steps in our data cleaning process. Data from MenuStat is available as separate Excel files for each year. Thus, the first step in data cleaning was to combine these separate dataframes into one, using the bind function. We then needed to convert all nutritional metrics to numeric type format, in order to do further analyses. The final step in cleaning this dataset was to create a new factor variable denoting the restaurant type. The restaurant was decided based on the type of menu items offered. The categories were: fast food, sit-down, beverages & dessert, and convenience stores. 

[NYC DOHMH Restaurant Inspections database](https://data.cityofnewyork.us/Health/Restaurants-rolled-up-/59dk-tdhz/data)
  NYC Open Data provides location data on annual restaurant inspections throughout New York City. This dataset allowed us to identify NYC-specific restaurants in the MenuStat dataset. Only restaurants that were found in both datasets were included in our analyses for this project (n=54). We achieved this by creating a new variable `dba` that included only restaurants identified in the MenuStat dataset. The restaurant inspections dataset was then filtered for only the restaurant type of `dba`, and other relevant variables, such as borough and zipcode, were selected to conduct location-based analyses. 
	Additionally, for the purpose of the statistical analyses, we summarised the number of occurrences of a restaurant type (`rest_type`) within a zip code thereby creating a new column with count data. Then, we used `pivot_wider` to move our row-wise count metrics to column variables for each restaurant type that corresponded to each zip code. For linear regression analysis, we calculated the proportions of a specific restaurant type within a zip code to be later used as our outcome of interest. For logistic analysis, we used `ifelse` statements to create binary outcome variables for restaurant types `sit_down` and `fast_food` that indicated if they were present in a zip code. However, in the case of `fast_food` we observed a high prevalence across all zip codes so to allow our logit model to converge, we used the median number of fast-food restaurants found across all zip codes as a condition to separate high and low prevalence (`fast_food` > 10).  

[American Community Survey (ACS) mean income, demographic and housing estimate data]
(https://data.census.gov/cedsci/table?q=population%20demographics%20income&g=0400000US36%248600000&tid=ACSST5Y2020.S1902) 
  The American Community Survey (ACS) provides annual sampling data that is based on approximately 3 million households across the United States. We used 5-year community survey estimates to obtain sociodemographic data at the zip code tabulation area (ZCTA) level for New York, NY. ACS data was obtained using a unique Census API Key and imported using `tidycensus` package version 1.3. Before loading 5-year ACS estimates, we specified New York state and at the ZCTA geography level for the years 2015 to 2019. We identified eleven variable codes that corresponded with sociodemographic variables of interest and were available across all years.
  We included sociodemographic variables such as median household income, total population (continuous), race (categorical), and sex (binary). For race, we created a summary metric for non-White, non-Other racial categories that summed counts for Black, Asian, American Indian/Alaskan Native, and Hawaiian/Pacific Islander later renamed `bipoc` (black, indigenous, people of color) as a measure to adjust for the low values observed in some categories.
The imported data frame from `tidycensus` was manipulated into a wide dataformat and further used to mutate proportions of race and biological sex by ZCTA. 


## Exploratory Analysis

We conducted exploratory analyses to visualize the nutritional changes by restaurant type over time. Visualizations were created using the ‘plotly’ package in R Studio. Initially, we plotted the distribution of calories by restaurant type (for all years) in a box plot. Additionally, we created another box plot with items with calorie counts in the top 5% of restaurants. Lastly, we plotted the frequency of each of these restaurants across NYC.
In order to visualize changes in nutritional content over time, we looked at calorie counts, fat, and protein, as distributed by the three restaurant types (convenience stores were omitted). Calorie distribution by restaurant type was plotted using individual box plots for different time points (years: 2008, 2012, 2016, and 2020). Fat distribution (trans fat) was plotted in the same way, as was protein. 
 
Lastly, nutritional metrics and restaurant type were combined. We created a box plot of Calorie Distribution by Food Category (appetizers, baked goods, beverages, entrees, etc…) overlaid by restaurant type (including convenience stores). This same plot was then re-created without the overlay, so as to more clearly visualize the calorie distribution in food categories by each restaurant type. The same process was repeated for both fat distribution and protein distribution. 


## Additional Statistical Analysis

We evaluated the relationship between the proportion of a sit down and fast food restaurant to occur in a zip code and relevant sociodemographic predictors. We used linear and logistic models at the zip code level to estimate proportion of restaurant type based on proportions of race (white, other, bipoc), sex (male and female), and median household income (aggregated estimate at the zip code or ZCTA level). We hypothesize that there are differential proportional declines by racial category and household income in correspondence with having a higher fast food restaurant occurrence proportional to any other type of restaurant. 

The hypothesis of these models was to see how the identified sociodemographic variables would impact the presence of a restaurant type throughout zip codes in NYC. To perform these analyses we had to further modify the restaurant location dataframe and create proportions of restaurant type for each zip code. We also mutated a factored binary variable for restaurant type by zip code with 1 representing the restaurant type is present and 0 representing the restaurant type was absent. This manipulated restaurant type dataframe was joined with the ACS dataframe by zip code to create a total dataframe with all variables needed for analysis. 

Then each model used the same set of predictors which included proportion of the population that identifies as white, proportion of the population that identifies in a BIPOC racial category, proportion of the population that identifies as ‘other’, proportion of the population that identifies with the biological sex female, and the median household income. The first linear model utilized OLS regression to look at the outcome, proportion of fast food restaurants, based on the described predictors. The second model incorporated a binary logistic regression to look at the outcome of a factor variable which indicated the presence or absence of a fast food restaurant. The method used for both the linear and logistic models was repeated for the outcome of sit down restaurants which was represented as a proportion and binary factor variable respectively for each model type. The linear fit for the predictors female, BIPOC and median income were graphed for each of the four models described above to further illustrate the relationships within the models. 


## Discussion

Distribution of calories remained roughly the same over all years, whereas trans fat and protein distributions seemed to increase. When visualizing nutritional content by food category, we see that sit-down restaurants have the highest calorie and fat distribution over all food categories. When it comes to protein, convenience stores and beverages/desserts have the highest protein distributions (albeit with much larger error bar ranges). This is likely due to the offering of protein bars and protein shakes at these types of establishments, that are not offered at regular or sit-down fast food restaurant chains. With an increase of public awareness and initiatives for healthy eating since 2008, we would have expected that calories and trans fat distributions would decrease over time, rather than remain constant. 

## References

1.	Vastine WJ. THE CONVENIENCE STORE INDUSTRY IN THE 1990s AND BEYOND. International Journal of Retail & Distribution Management. 1991;19(6). doi:10.1108/EUM0000000002953
2.	Ozbun T. Convenience stores in the U.S. - Statistics & Facts. Statista. Published January 27, 2022. Accessed November 10, 2022. https://www.statista.com/topics/3869/convenience-stores-in-the-us/
3.	U.S. Convenience Store Count. Accessed November 10, 2022. https://www.convenience.org/Research/FactSheets/IndustryStoreCount
4.	Frank L, Glanz K, McCarron M, Sallis J, Sealens B, Chapman J. The Spatial Distribution of Food Outlet Type and Quality around Schools in Differing Built Environment and Demographic Contexts. Berkeley Planning Journal. 2006;19(1). doi:10.5070/BP319111490
5.	Walker RE, Block J, Kawachi I. The Spatial Accessibility of Fast food Restaurants and Convenience Stores in Relation to Neighborhood Schools. Appl Spatial Analysis. 2014;7(2):169-182. doi:10.1007/s12061-013-9095-6
6.	Rodríguez-Guerra AI, López-Olmedo N, Medina C, Hernández-Alcaraz C, Ortega-Avila AG, Barquera S. Association between density of convenience and small grocery stores with diet quality in adults living in Mexico City: A cross sectional study. Frontiers in Public Health. 2022;10. Accessed November 10, 2022. https://www.frontiersin.org/articles/10.3389/fpubh.2022.857754
7.	Sharkey JR, Dean WR, Nalty C. Convenience stores and the marketing of foods and beverages through product assortment. Am J Prev Med. 2012;43(3 Suppl 2):S109-115. doi:10.1016/j.amepre.2012.05.012
8.	Morland K, Diez Roux AV, Wing S. Supermarkets, other food stores, and obesity: the atherosclerosis risk in communities study. Am J Prev Med. 2006;30(4):333-339. doi:10.1016/j.amepre.2005.11.003
9.	Powell LM, Auld MC, Chaloupka FJ, O’Malley PM, Johnston LD. Associations between access to food stores and adolescent body mass index. Am J Prev Med. 2007;33(4 Suppl):S301-307. doi:10.1016/j.amepre.2007.07.007
10.	Larson NI, Story MT, Nelson MC. Neighborhood Environments: Disparities in Access to Healthy Foods in the U.S. American Journal of Preventive Medicine. 2009;36(1):74-81.e10. doi:10.1016/j.amepre.2008.09.025

