---
title: "Statistical Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    theme : cosmo
---

### Statistical Analysis
```{r, warning = FALSE, message = FALSE}
menustat_df = read_csv("data/menustat_combined.csv")
rest_locations = read_csv("data/restaurant_location.csv")
```



```{r frequency, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidycensus)

rest_locations %>%
  select(restaurant, rest_type) %>%
  arrange(rest_type) %>%
  distinct 

menustat_df %>%
  select(restaurant, rest_type) %>%
  arrange(rest_type) %>%
  distinct 


menustat_df %>%
  select(restaurant, rest_type) %>%
  arrange(rest_type) %>%
  distinct 


menustat_df %>%
  summarise(across(everything(), ~sum(is.na(.x)))) %>%
  knitr::kable() #no more NA's for variables we are using

###frequency visualizations stratified by restaurant type

ff_cal = menustat_df %>%
  select(rest_type, calories) %>%
  filter(rest_type == "fast food") %>%
  ggplot(aes(x = calories)) +
  geom_histogram(fill = "light blue", color = "black") + 
labs(
    x = "Calories per Item",
    y = "Frequency", 
    title = "Fast food restaurants"
  ) 


sd_cal = menustat_df %>%
  select(rest_type, calories) %>%
  filter(rest_type == "sit-down") %>%
  ggplot(aes(x = calories)) +
  geom_histogram(fill = "red", color = "black") + 
labs(
    x = "Calories per Item",
    y = "Frequency",
    title = "Sit-down restaurants"
  ) 

bevdes_cal = menustat_df %>%
  select(rest_type, calories) %>%
  filter(rest_type == "beverages_dessert") %>%
  ggplot(aes(x = calories)) +
  geom_histogram(fill = "yellow", color = "black") + 
labs(
    x = "Calories per Item",
    y = "Frequency", 
    title = "Beverages and dessert shops"
  ) #has more spread in its mean


conv_cal = menustat_df %>%
  select(rest_type, calories) %>%
  filter(rest_type == "convenience") %>%
  ggplot(aes(x = calories)) +
  geom_histogram(fill = "green", color = "black") + 
labs(
    x = "Calories per Item",
    y = "Frequency",
    title = "Convenience stores"
  ) 



menustat_df %>%
  select(rest_type, calories) %>%
  ggplot(aes(x = calories, color = rest_type)) +
  geom_histogram(binwidth = 30)

ff_cal + sd_cal + bevdes_cal + conv_cal
```

```{r summarise, warning = FALSE, message = FALSE}

##calories 

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(calories), list(name = mean))

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(calories), list(name = median))

##total fat

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(total_fat), list(name = mean))

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(total_fat), list(name = median))

##sodium

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(sodium), list(name = mean))

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(sodium), list(name = median))

##carbs

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(carbohydrates), list(name = mean))

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(carbohydrates), list(name = median))

##sugar

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(sugar), list(name = mean))

menustat_df %>%
  group_by(rest_type) %>%
  summarise_at(vars(sugar), list(name = median))
```

# New Model Building
```{r, warning = FALSE, message = FALSE}


#DATAFRAME 1:REST 
rest_locations_new = rest_locations %>%
  group_by(zipcode, rest_type) %>%
  summarise(num_rest_type = n()) %>% 
  pivot_wider(
    names_from = "rest_type", 
    values_from = "num_rest_type"
  ) %>% 
  drop_na(zipcode) %>% 
  replace(is.na(.), 0) %>% 
  rename(fast_food = `fast food`,
         sit_down = `sit-down`) %>%
  mutate(total = beverages_dessert + fast_food + sit_down, 
         prop_bev = beverages_dessert/total, 
         prop_fast = fast_food/total, 
         prop_sit = sit_down/total, 
         logit_sit = ifelse(sit_down > 0, 1, 0),
         logit_fast = ifelse(fast_food > 10, 1, 0)) %>% 
  select(-c(total)) 



#DATAFRAME 2: ACS
nyc_acs = read_csv("data/nyc_acs_reg")

total_rest_acs = left_join(rest_locations_new, nyc_acs, by = "zipcode") %>% 
  drop_na()

```

```{r, warning = FALSE, message = FALSE}
##Linear model

fit.fast <- lm(prop_fast ~ prop_white + prop_bipoc + prop_female + prop_other + med_income, data = total_rest_acs)


fit_table_fast = fit.fast %>% 
  broom::tidy() %>% 
    knitr::kable(digits = 3)


fit.sit <- lm(prop_sit ~ prop_white + prop_bipoc + prop_female + prop_other + med_income, data = total_rest_acs)


fit_table_sit = fit.sit %>% 
  broom::tidy() %>% 
    knitr::kable(digits = 3)


##GLM  

fit.logit.sit <- glm(logit_sit ~ prop_white + prop_bipoc + prop_female + prop_other + med_income, data = total_rest_acs, family = "binomial")

summary(fit.logit.sit)

logit_table_sit = fit.logit.sit %>% 
  broom::tidy() %>% 
    knitr::kable(digits = 3)


fit.logit.fast <- glm(logit_fast ~ prop_white + prop_bipoc + prop_female + prop_other + med_income, data = total_rest_acs, family = "binomial")

summary(fit.logit.fast)

logit_table_fast = fit.logit.fast %>% 
  broom::tidy() %>% 
    knitr::kable(digits = 3)
```

# plots 

```{r, warning = FALSE, message = FALSE}
##Linear regression plots: fast food 

fem_ff = ggplot(total_rest_acs, aes(x = prop_female, y = prop_fast)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion of Fast Food Restaurants by Proportion of Female in Population",
    x = "Proportion of Female Residents",
    y = "Proportion of Fast Food Restaurants"
  )


#bipoc 
bipoc_ff = ggplot(total_rest_acs, aes(x = prop_bipoc, y = prop_fast)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion of Fast Food Restaurants by Proportion of BIPOC in Population",
    x = "Proportion of BIPOC Residents",
    y = "Proportion of Fast Food Restaurants"
  )


#medincome
med_in_ff = ggplot(total_rest_acs, aes(x = med_income, y = prop_fast)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion Fast Food Restaurants by Median income",
    x = "Median Income",
    y = "Proportion of Fast Food Restaurants"
  )


##Linear regression plots: sit down

#female 
fem_sit = ggplot(total_rest_acs, aes(x = prop_female, y = prop_sit)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion of Sit-down Restaurants by Proportion of Female in Population",
    x = "Proportion of Female Residents",
    y = "Proportion of Sit-down Restaurants")


#bipoc 
bipoc_sit = ggplot(total_rest_acs, aes(x = prop_bipoc, y = prop_sit)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion of Sit-down Restaurants by Proportion of BIPOC in Population",
    x = "Proportion of BIPOC Residents",
    y = "Proportion of Sit-down Restaurants"
  )


#medincome
med_in_sit = ggplot(total_rest_acs, aes(x = med_income, y = prop_sit)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(
    title = "Proportion Sit-down Restaurants by Median income",
    x = "Median Income",
    y = "Proportion of Sit-down Restaurants"
  )

##Logistic regression plots

log_SIT = ggplot(total_rest_acs, aes(x= prop_female, y= logit_sit)) + 
  geom_point() +
  stat_smooth(method="glm", color="green", se=TRUE, method.args = list(family=binomial)) +
labs(
    title = "Presence of Sit-down Restaurants by Proportion of Female Residents",
    x = "Proportion of Female",
    y = "Presence of Sit-Down Restaurants"
  )



log_FF = ggplot(total_rest_acs, aes(x= prop_female, y= logit_fast)) + 
  geom_point() +
  stat_smooth(method="glm", color="green", se=TRUE, method.args = list(family=binomial)) +
labs(
    title = "Presence of Fast Food Restaurants by Proportion of Female Residents",
    x = "Proportion of Female",
    y = "Presence of Fast Food Restaurants"
  )


med_in_ff + bipoc_ff + fem_ff + med_in_sit + bipoc_sit + fem_sit



log_FF + log_SIT

```


